import { describe, expect, it } from "vitest";
import { cosineSimilarity } from "@/lib/infrastructure/embeddings/generator";
import { scoreByVector } from "@/lib/infrastructure/ai/vector-search";
import { makeRule } from "./fixtures";

const embedding = (ruleId: string, vector: number[], model: string) => ({
  id: `e-${ruleId}-${model}`,
  ruleId,
  vector,
  model,
  createdAt: new Date(0),
});

describe("cosineSimilarity", () => {
  it("returns 1 for the same direction and 0 for orthogonal vectors", () => {
    expect(cosineSimilarity([1, 2], [2, 4])).toBeCloseTo(1);
    expect(cosineSimilarity([1, 0], [0, 1])).toBe(0);
  });

  it("returns 0 (not NaN) for zero vectors", () => {
    expect(cosineSimilarity([0, 0], [1, 1])).toBe(0);
    expect(cosineSimilarity([0, 0], [0, 0])).toBe(0);
  });

  it("throws on dimension mismatch", () => {
    expect(() => cosineSimilarity([1], [1, 2])).toThrow();
  });
});

describe("scoreByVector", () => {
  it("ignores embeddings generated by a different model", () => {
    const hits = scoreByVector(
      [1, 0],
      [makeRule({ id: "a" }), makeRule({ id: "b" })],
      [embedding("a", [1, 0], "current"), embedding("b", [1, 0], "old")],
      "current"
    );
    expect(hits).toEqual([{ ruleId: "a", score: 1 }]);
  });

  it("clamps negative similarity to 0", () => {
    const hits = scoreByVector(
      [1, 0],
      [makeRule({ id: "a" })],
      [embedding("a", [-1, 0], "m")],
      "m"
    );
    expect(hits[0].score).toBe(0);
  });
});
